services:
  search-api:
    image: theosun/browser-search-api:latest
    environment:
      NODE_ENV: production
      PW_REMOTE_URL: ws://browserless:3000?token=us5W3elErSluCvyCwMPzC0ntA
      TF_URL: http://trafilatura-api:5000
    restart: always
  browserless:
    image: ghcr.io/browserless/chromium
    environment:
      - CONCURRENT=10
      - TOKEN=us5W3elErSluCvyCwMPzC0ntA
      - MAX_CPU_PERCENT=40
      - MAX_MEMORY_PERCENT=40
      - HEALTH=true
      - QUEUED=20
    restart: always
  trafilatura-api:
    image: theosun/trafilatura-api:latest
    restart: always
